module.exports = {
    profanitySureness: 2,
    allow: [
        "alumnae-alumni",
        "aunt-uncle",
        "boy-girl",
        "clearly",
        "dad-mom",
        "daughter-son",
        "deaf-to",
        "easy",
        "gal-guy",
        "gals-man",
        "he-she",
        "her-him",
        "just",
        "Master",
        "master",
        "nuts",
        "obvious",
        "of-course",
        "prince-princess",
        "savage",
        "simple",
        "special",
        "straightforward",
        "Whitespace",
        "whitespace",
        "yank"
    ]
};
